const multer = require("multer");
const path = require("path");
const crypto = require("crypto");//to generate a unique name for file

//disk storage
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, path.join(__dirname,'../public/images/uploads'));
  },
  filename: function (req, file, cb) {
    crypto.randomBytes(12,function(err,name){
        const fn = name.toString("hex")+path.extname(file.originalname);//original file name se path nikal ke add it to the unique file name generated by crypto
        cb(null, fn);
    });
  }
})

//export upload variables
const upload = multer({ storage: storage })

module.exports = upload;

